// Test generated by RoostGPT for test se-code using AI Type Open AI and AI Model gpt-4


using NUnit.Framework;
using HashMapNamespace;

namespace HashMapNamespace.Test
{
    [TestFixture]
    public class HashMap64_HashMap64_e04ba9c10b
    {
        [Test]
        public void HashMap64_CapacityZero_InitializesEmptyHashMap()
        {
            var hashMap = new HashMap64(0);

            Assert.AreEqual(-1, hashMap.EmptySlot);
            Assert.AreEqual(0, hashMap.Capacity);
            Assert.AreEqual(0, hashMap.LimitCapacity);
            Assert.AreEqual(0, hashMap.CollisionEndIndex);
        }

        [Test]
        public void HashMap64_CapacityNegative_ThrowsArgumentOutOfRangeException()
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => new HashMap64(-1));
        }

        [Test]
        public void HashMap64_CapacityPositive_InitializesHashMapWithSpecifiedCapacity()
        {
            var hashMap = new HashMap64(10);

            Assert.AreEqual(-1, hashMap.EmptySlot);
            Assert.AreEqual(10, hashMap.Capacity);
            Assert.AreEqual(10, hashMap.LimitCapacity);
            Assert.AreEqual(10, hashMap.CollisionEndIndex);
        }

        [Test]
        public void HashMap64_CapacityGreaterThanMaxInt_ThrowsArgumentOutOfRangeException()
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => new HashMap64(int.MaxValue + 1L));
        }
    }
}
